spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:8080/security
    username: test
    password: test1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update  #update, validate, create, none    
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
  view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
logging:
    level:
      org.springframework.boot: TRACE #TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
      org.springframework.web: TRACE #TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
      org.springframework.data: TRACE #TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
